micronaut:
  application:
    name: md-user-service
  server:
    context-path: /api/md-user-service/v1
  email:
    default:
      from: mariposasdigitais@gmail.com
    javamail:
      host: smtp.gmail.com
      port: 587
      username: mariposasdigitais@gmail.com
      password: jEss@l3t
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
  #    cors:
  #      enabled: true
  #      configurations:
  #        default:
  #          allowedOrigins:
  #            - "http://localhost:3000"
  #            - "*"
  #          allowedMethods:
  #            - GET
  #            - POST
  #            - PUT
  #            - DELETE
  #            - OPTIONS
  #          allowedHeaders:
  #            - "Content-Type"
  #            - "token"
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

endpoints:
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false

datasources:
  default:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://mariposas.c32w0ooyq20s.us-east-2.rds.amazonaws.com:5432/mariposas
    username: mariposas
    password: jEss4l3t
    maximumPoolSize: 3

jpa:
  default:
    entity-scan:
      packages: mariposas.model
    properties:
      hibernate:
        hbm2ddl:
          auto: none
      show_sql: false
      format_sql: true
      current_session_context_class: thread
      dialect: org.hibernate.dialect.PostgreSQL95Dialect

aws:
  cognito:
    userPoolId: us-east-1_EZq6amARk
    clientId: 77ae69a0o2dh1hfbsp391h2214
  s3:
    bucket-name: mariposas-digitais