openapi: 3.0.3

info:
  title: md-user-service
  description: Microsserviço responsável por gerir todas as ações relacionadas a um usuário.
  version: 1.0.11

tags:
  - name: User

paths:
  /user:
    post:
      tags:
        - User
      summary: Create user
      operationId: createUser
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserModel'
      responses:
        '200':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
        '400':
          description: Bad request
        '404':
          description: Not found
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal Server Error

    delete:
      tags:
        - User
      summary: Delete user
      operationId: deleteUser
      parameters:
        - $ref: '#/components/parameters/token'
        - $ref: '#/components/parameters/email'
      responses:
        '200':
          description: Profile successfully deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
        '400':
          description: Bad request
        '404':
          description: Not found
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal Server Error

  /user/login:
    post:
      tags:
        - User
      summary: Login
      operationId: login
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginModel'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponseModel'
        '400':
          description: Bad request
        '404':
          description: Not found
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal Server Error

  /user/logout:
    post:
      tags:
        - User
      summary: Logout
      operationId: logout
      parameters:
        - $ref: '#/components/parameters/token'
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
        '400':
          description: Bad request
        '404':
          description: Not found
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal Server Error

  /user/profile:
    get:
      tags:
        - User
      summary: Get user profile
      operationId: userProfile
      parameters:
        - $ref: '#/components/parameters/token'
        - $ref: '#/components/parameters/email'
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfileModel'
        '400':
          description: Bad request
        '404':
          description: Not found
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal Server Error

  /user/profile/mentee:
    post:
      tags:
        - User
      summary: Complete mentee profile
      operationId: menteeProfile
      parameters:
        - $ref: '#/components/parameters/token'
        - $ref: '#/components/parameters/email'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MenteeProfileModel'
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
        '400':
          description: Bad request
        '404':
          description: Not found
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal Server Error

  /user/profile/mentor:
    post:
      tags:
        - User
      summary: Complete mentor profile
      operationId: mentorProfile
      parameters:
        - $ref: '#/components/parameters/token'
        - $ref: '#/components/parameters/email'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MentorProfileModel'
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
        '400':
          description: Bad request
        '404':
          description: Not found
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal Server Error

  /user/profile/image:
    post:
      tags:
        - User
      summary: Insert a image profile
      operationId: imageProfile
      parameters:
        - $ref: '#/components/parameters/token'
        - $ref: '#/components/parameters/email'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - arquivo
              properties:
                arquivo:
                  type: string
                  format: binary

      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
        '400':
          description: Bad request
        '404':
          description: Not found
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal Server Error

  /user/password:
    post:
      tags:
        - User
      summary: Change password
      operationId: changePassword
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordModel'
      responses:
        '200':
          description: Password changed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
        '400':
          description: Bad request
        '404':
          description: Not found
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal Server Error

    get:
      tags:
        - User
      summary: Forgot password
      operationId: forgotPassword
      parameters:
        - $ref: '#/components/parameters/email'
      responses:
        '200':
          description: Password changed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
        '400':
          description: Bad request
        '404':
          description: Not found
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal Server Error

  /sponsorship:
    post:
      tags:
        - Sponsorship
      summary: Sponsoring
      operationId: sponsoringMentee
      parameters:
        - $ref: '#/components/parameters/token'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SponsorshipModel'
      responses:
        '200':
          description: List of mentees successfully returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
        '400':
          description: Bad request
        '404':
          description: Not found
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal Server Error

    delete:
      tags:
        - Sponsorship
      summary: Cancel sponsorship
      operationId: cancelSponsorship
      parameters:
        - $ref: '#/components/parameters/token'
        - $ref: '#/components/parameters/emailMentee'
        - $ref: '#/components/parameters/emailMentor'
      responses:
        '200':
          description: Sponsorship successfully canceled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
        '400':
          description: Bad request
        '404':
          description: Not found
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal Server Error

  /sponsorship/mentee:
    get:
      tags:
        - Sponsorship
      summary: Obtain a list of mentees available for sponsorship
      operationId: getMenteesList
      parameters:
        - $ref: '#/components/parameters/token'
        - $ref: '#/components/parameters/limitQuery'
        - $ref: '#/components/parameters/pageQuery'
        - $ref: '#/components/parameters/email'
      responses:
        '200':
          description: List of mentees successfully returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedMentees'
        '400':
          description: Bad request
        '404':
          description: Not found
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal Server Error

  /sponsorship/mentor:
    get:
      tags:
        - Sponsorship
      summary: Get the profile of the mentor who sponsored her
      operationId: getMentorProfile
      parameters:
        - $ref: '#/components/parameters/token'
        - $ref: '#/components/parameters/email'
      responses:
        '200':
          description: Mentor profile successfully returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MentorModel'
        '400':
          description: Bad request
        '404':
          description: Not found
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal Server Error

  /sponsorship/notification:
    get:
      tags:
        - Sponsorship
      summary: Sponsorship notification
      operationId: sponsorshipNotification
      parameters:
        - $ref: '#/components/parameters/token'
        - $ref: '#/components/parameters/email'
      responses:
        '200':
          description: Sponsorship notification successfully returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SponsorshipNotificationModel'
        '400':
          description: Bad request
        '404':
          description: Not found
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal Server Error


components:
  parameters:
    token:
      name: token
      in: header
      required: true
      description: JWT User Access Token
      schema:
        type: string

    email:
      name: email
      in: header
      required: true
      description: User email
      schema:
        type: string

    emailMentee:
      name: emailMentee
      in: header
      required: true
      description: Mentee email
      schema:
        type: string

    emailMentor:
      name: emailMentor
      in: header
      required: true
      description: Mentor email
      schema:
        type: string

    limitQuery:
      name: limit
      in: query
      required: false
      description: Number of records per page
      schema:
        type: integer
        example: 2
        minimum: 2
        default: 2

    pageQuery:
      name: page
      in: query
      required: false
      description: Current page
      schema:
        type: integer
        example: 1
        minimum: 1
        default: 1

  schemas:
    UserModel:
      type: object
      properties:
        name:
          type: string
          example: Maria Eugênia Nascimento
        email:
          type: string
          example: mariaeugenia@email.com
        password:
          type: string
          example: m4ria3ug3ni4
        phone:
          type: string
          example: 31995236485
        isMentor:
          enum:
            - 1
            - 2

    UserProfileModel:
      type: object
      properties:
        name:
          type: string
          example: Maria Eugênia Nascimento
        image:
          type: string
          format: byte
        email:
          type: string
          example: mariaeugenia@email.com
        phone:
          type: string
          example: 31995236485
        profile:
          type: string
          example: Olá, sou a Maria Eugênia [...]
        age:
          type: string
          example: 24
        education:
          type: string
          example: Bacharelado em Sistemas de Informação
        menteeLevel:
          type: string
          example: LAGARTA
        isSponsored:
          type: boolean
          example: true
        mentoringCapacity:
          type: string
          example: 2
        mentoringAvailable:
          type: string
          example: 1

    LoginModel:
      properties:
        email:
          type: string
          example: mariaeugenia@email.com
        password:
          type: string
          example: m4ria3ug3ni4

    MenteeProfileModel:
      properties:
        profile:
          type: string
          example: Olá, sou a Maria Eugênia [...]
        age:
          type: string
          example: 24
        menteeLevel:
          enum:
            - 1
            - 2

    MentorProfileModel:
      properties:
        education:
          type: string
          example: Bacharelado em Sistemas de Informação
        age:
          type: string
          example: 24
        mentoringCapacity:
          enum:
            - 1
            - 2
          default: 1
        profile:
          type: string
          example: Olá, sou a Maria Eugênia [...]

    MenteesModel:
      type: object
      properties:
        name:
          type: string
          example: Maria Eugênia Nascimento
        email:
          type: string
          example: mariaeugenia@email.com
        phone:
          type: string
          example: 31995236485
        profile:
          type: string
          example: Olá, sou a Maria Eugênia [...]
        age:
          type: string
          example: 24
        menteeLevel:
          type: string
          example: LAGARTA
        image:
          type: string
          format: byte

    PaginatedMentees:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/MenteesModel'
        currentPage:
          type: integer
          example: 1
        totalRecords:
          type: integer
          example: 1
        totalRecordsPerPage:
          type: integer
          example: 2

    SponsorshipModel:
      type: object
      properties:
        emailMentee:
          type: string
          example: mariaeugenia@email.com
        emailMentor:
          type: string
          example: anastaciabatista@email.com

    MentorModel:
      type: object
      properties:
        name:
          type: string
          example: Maria Eugênia Nascimento
        email:
          type: string
          example: mariaeugenia@email.com
        phone:
          type: string
          example: 31995236485
        profile:
          type: string
          example: Olá, sou a Maria Eugênia [...]
        age:
          type: string
          example: 24
        education:
          type: string
          example: Bacharelado em Sistemas de Informação
        image:
          type: string
          format: byte

    SponsorshipNotificationModel:
      type: object
      properties:
        email:
          type: string
          example: mariaeugenia@gmail.com
        name:
          type: string
          example: Maria Eugênia
        image:
          type: string
          format: byte
        phone:
          type: string
          example: 31995236485
        profile:
          type: string
          example: Olá, sou a Maria Eugênia [...]
        age:
          type: string
          example: 24
        education:
          type: string
          example: Bacharelado em Sistemas de Informação

    ResponseModel:
      type: object
      properties:
        mensagem:
          type: string
        status:
          type: number

    PasswordModel:
      type: object
      properties:
        email:
          type: string
        password:
          type: string

    LoginResponseModel:
      type: object
      properties:
        mensagem:
          type: string
        status:
          type: number
        token:
          type: string