openapi: 3.0.1
tags:
- name: User
  description: The User API
paths:
  /api/md-user-service/v1/user:
    post:
      tags:
      - User
      summary: Create user
      description: Create user
      operationId: createUser
      requestBody:
        description: (optional)
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserModel"
      responses:
        "200":
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseModel"
        "400":
          description: Bad request
        "404":
          description: Not found
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
  /api/md-user-service/v1/user/login:
    post:
      tags:
      - User
      summary: Login
      description: Login
      operationId: login
      requestBody:
        description: (optional)
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginModel"
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponseModel"
        "400":
          description: Bad request
        "404":
          description: Not found
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
  /api/md-user-service/v1/user/mentee:
    get:
      tags:
      - User
      summary: Obtain a list of mentees available for sponsorship
      description: Obtain a list of mentees available for sponsorship
      operationId: getMenteesList
      parameters:
      - name: token
        in: header
        description: JWT User Access Token (required)
        required: true
        schema:
          type: string
      - name: email
        in: header
        description: User email (required)
        required: true
        schema:
          type: string
      - name: limit
        in: query
        description: "Number of records per page (optional, default to 2)"
        schema:
          minimum: 2
          type: integer
          format: int32
          nullable: true
          default: 2
      - name: page
        in: query
        description: "Current page (optional, default to 1)"
        schema:
          minimum: 1
          type: integer
          format: int32
          nullable: true
          default: 1
      responses:
        "200":
          description: List of mentees successfully returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginatedMentees"
        "400":
          description: Bad request
        "404":
          description: Not found
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
  /api/md-user-service/v1/user/password/forgot:
    post:
      tags:
      - User
      summary: Request password reset link
      description: Request password reset link
      operationId: forgotPassword
      parameters:
      - name: token
        in: header
        description: JWT User Access Token (required)
        required: true
        schema:
          type: string
      requestBody:
        description: (optional)
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ForgotPasswordModel"
      responses:
        "200":
          description: Password recovery request sent successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseModel"
        "400":
          description: Bad request
        "404":
          description: Not found
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
  /api/md-user-service/v1/user/profile/mentee:
    post:
      tags:
      - User
      summary: Complete mentee profile
      description: Complete mentee profile
      operationId: menteeProfile
      parameters:
      - name: token
        in: header
        description: JWT User Access Token (required)
        required: true
        schema:
          type: string
      requestBody:
        description: (optional)
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MenteeProfileModel"
      responses:
        "200":
          description: Profile updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseModel"
        "400":
          description: Bad request
        "404":
          description: Not found
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
  /api/md-user-service/v1/user/profile/mentor:
    post:
      tags:
      - User
      summary: Complete mentor profile
      description: Complete mentor profile
      operationId: mentorProfile
      parameters:
      - name: token
        in: header
        description: JWT User Access Token (required)
        required: true
        schema:
          type: string
      requestBody:
        description: (optional)
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MentorProfileModel"
      responses:
        "200":
          description: Profile updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseModel"
        "400":
          description: Bad request
        "404":
          description: Not found
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
components:
  schemas:
    ForgotPasswordModel:
      type: object
      properties:
        email:
          type: string
          nullable: true
      description: ForgotPasswordModel
    LoginModel:
      type: object
      properties:
        email:
          type: string
          nullable: true
          example: mariaeugenia@email.com
        password:
          type: string
          nullable: true
          example: m4ria3ug3ni4
      description: LoginModel
    LoginResponseModel:
      type: object
      properties:
        mensagem:
          type: string
          nullable: true
        status:
          type: number
          nullable: true
        token:
          type: string
          nullable: true
      description: LoginResponseModel
    MenteeProfileModel:
      type: object
      properties:
        email:
          type: string
          nullable: true
          example: mariaeugenia@email.com
        profile:
          type: string
          nullable: true
          example: "Olá, sou a Maria Eugênia [...]"
        isSponsored:
          type: boolean
          nullable: true
        age:
          type: string
          nullable: true
          example: "24"
        menteeLevel:
          nullable: true
          allOf:
          - $ref: "#/components/schemas/UserModelIsMentor"
      description: MenteeProfileModel
    MenteesModel:
      type: object
      properties:
        name:
          type: string
          nullable: true
          example: Maria Eugênia Nascimento
        email:
          type: string
          nullable: true
          example: mariaeugenia@email.com
        phone:
          type: string
          nullable: true
          example: "31995236485"
        profile:
          type: string
          nullable: true
          example: "Olá, sou a Maria Eugênia [...]"
        age:
          type: string
          nullable: true
          example: "24"
        menteeLevel:
          type: string
          nullable: true
          example: LAGARTA
        image:
          type: string
          format: binary
          nullable: true
      description: MenteesModel
    MentorProfileModel:
      type: object
      properties:
        email:
          type: string
          nullable: true
          example: mariaeugenia@email.com
        education:
          type: string
          nullable: true
          example: Bacharelado em Sistemas de Informação
        age:
          type: string
          nullable: true
          example: "24"
        mentoringCapacity:
          nullable: true
          allOf:
          - $ref: "#/components/schemas/MentorProfileModelMentoringCapacity"
        profile:
          type: string
          nullable: true
          example: "Olá, sou a Maria Eugênia [...]"
      description: MentorProfileModel
    MentorProfileModelMentoringCapacity:
      type: number
      description: Gets or Sets MentorProfileModel_mentoringCapacity
      enum:
      - 1
      - 2
    PaginatedMentees:
      type: object
      properties:
        data:
          type: array
          nullable: true
          items:
            $ref: "#/components/schemas/MenteesModel"
        currentPage:
          type: integer
          format: int32
          nullable: true
          example: 1
        totalRecords:
          type: integer
          format: int32
          nullable: true
          example: 1
        totalRecordsPerPage:
          type: integer
          format: int32
          nullable: true
          example: 2
      description: PaginatedMentees
    ResponseModel:
      type: object
      properties:
        mensagem:
          type: string
          nullable: true
        status:
          type: number
          nullable: true
      description: ResponseModel
    UserModel:
      type: object
      properties:
        name:
          type: string
          nullable: true
          example: Maria Eugênia Nascimento
        email:
          type: string
          nullable: true
          example: mariaeugenia@email.com
        password:
          type: string
          nullable: true
          example: m4ria3ug3ni4
        phone:
          type: string
          nullable: true
          example: "31995236485"
        image:
          type: string
          nullable: true
        isMentor:
          nullable: true
          allOf:
          - $ref: "#/components/schemas/UserModelIsMentor"
      description: UserModel
    UserModelIsMentor:
      type: number
      description: Gets or Sets UserModel_isMentor
      enum:
      - 1
      - 2
