#micronaut:
#  security:
#    oauth2:
#      clients:
#        default:
#          client-id: ${OAUTH_CLIENT_ID:XXX}
#          client-secret: ${OAUTH_CLIENT_SECRET:YYY}
#          openid:
#            issuer: https://cognito-idp.${COGNITO_REGION:us-east-1}.amazonaws.com/${COGNITO_POOL_ID:ZZZ}/

micronaut:
  application:
    name: md-user-service
  server:
    context-path: /api/md-user-service/v1
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
#  security:
#    authentication: idtoken
#jpa.default.properties.hibernate.hbm2ddl.auto: update

endpoints:
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false

datasources:
  default:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://mariposas.c32w0ooyq20s.us-east-2.rds.amazonaws.com:5432/mariposas
    username: mariposas
    password: jEss4l3t
    maximumPoolSize: 3

jpa:
  default:
    entity-scan:
      packages: mariposas.model
    properties:
      hibernate:
        hbm2ddl:
          auto: none
      show_sql: false
      format_sql: true
      current_session_context_class: thread
      dialect: org.hibernate.dialect.PostgreSQL95Dialect

aws:
  cognito:
    userPoolId: us-east-1_EZq6amARk
    clientId: 77ae69a0o2dh1hfbsp391h2214
    region: us-east-1